### ISSUE TITLE
README.md - Could benefit from conceptual references

### ISSUE THREAD

**Issue by ElSrJuez** [mdgdeveloper/entraid_login#1]
I got a bit lost - README.md could benefit with a slightly more ambitios introduction and scope, and the references used to create the example?

**Comment by ElSrJuez** [comment]
Any news on this issue?
I just checked and I cannot contribute.

**Comment by mdgdeveloper** [comment]
Updated README.md with references and a brief explanation of the MSAL authentication process

**Comment by ElSrJuez** [comment]
Thanks!
